version: '3'

services:
  web:
    image: scooters-web
    build: .
    ports:
      - 3000:3000
    volumes:
      - npm_cache:/root/.npm
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
    env_file:
      - .env

volumes:
  npm_cache: